### ISSUE TITLE
"PlatformError: Wayland: Failed to connect to display" fatal error on X11

### ISSUE THREAD

**Issue by VRcontrib** [galister/X11Overlay#14]
WlxOverlay correctly detects that the system is using X11, but it seems like it still tries to connect to a Wayland display. I've attached the applicable logs below, I can provide any more information that is needed upon request.

```
WlxOverlay v1.3.1
OpenVR Version: 1.26.5
IVROverlay_025: pass
IVRCompositor_027: pass
IVRInput_010: pass
Loaded 10 input actions for /actions/default
export_inputs will not be used.
HMD running @ 120.019 Hz
X11 desktop detected.
Using paplay for audio output.
Listening for notifications @ 127.0.0.1:42069
Unhandled exception. Silk.NET.GLFW.GlfwException: GLFW Init failed, PlatformError: Wayland: Failed to connect to display
   at Silk.NET.GLFW.GlfwProvider.GetGlfw()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Silk.NET.Windowing.Glfw.GlfwWindow..ctor(WindowOptions optionsCache, GlfwWindow parent, GlfwMonitor monitor)
   at Silk.NET.Windowing.Glfw.GlfwPlatform.CreateWindow(WindowOptions options)
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at WlxOverlay.GFX.OpenGL.GlGraphicsEngine.StartEventLoop() in /home/runner/work/WlxOverlay/WlxOverlay/GFX/OpenGL/GlGraphicsEngine.cs:line 38
   at Program.<Main>$(String[] args) in /home/runner/work/WlxOverlay/WlxOverlay/Program.cs:line 120
   at Program.<Main>(String[] args)
fish: Job 1, './WlxOverlay-*.AppImage' terminated by signal SIGABRT (Abort)
```

**Comment by galister** [comment]
Have you tried these two?

https://github.com/galister/WlxOverlay/wiki/Troubleshooting#failed-to-connect-to-wayland-display-server-when-on-x11
https://github.com/galister/WlxOverlay/wiki/Troubleshooting#glfw-init-failed-platformerror

**Comment by VRcontrib** [comment]
Thank you! I definitely should've checked the docs before creating the issue, sorry about that. And thank you for providing such comprehensive documentation, I really appreciate it!
