### ISSUE TITLE
Unavailable cursor mode 2

### ISSUE THREAD

**Issue by faux-eccles** [galister/X11Overlay#25]
Running in Wayland on the Nobara distro (Fedora 38)  and using SteamVR

``` 
WlxOverlay v1.4.2
/home/eccles/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper.sh: line 17: STEAMVR_VRENV: unbound variable
/home/eccles/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
OpenVR Version: 2.3.1
IVROverlay_025: pass
IVRCompositor_027: pass
IVRInput_010: pass
Loaded 10 input actions for /actions/default
export_inputs will not be used.
HMD running @ 90 Hz
Wayland detected.
!!! Patched GLFW from https://github.com/Admicos/minecraft-wayland
!!! If any issues with the window, or some issues with rendering, occur, first try with the built-in GLFW, and if that solves the issue, report there first.
!!! Use outside Minecraft is untested, and things might break.
EGL 1.5 initialized.
Using PipeWire capture.
PipeWire version: 1.0.0
Using DMA-Buf with supported formats: DRM_FORMAT_ARGB8888, DRM_FORMAT_ABGR8888, DRM_FORMAT_XRGB8888, DRM_FORMAT_XBGR8888
Unhandled exception. Tmds.DBus.Protocol.DBusException: org.freedesktop.portal.Error.InvalidArgument: Unavailable cursor mode 2
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token) in /home/runner/work/WlxOverlay/WlxOverlay/Protocols/DBus/DBusConnection.cs:line 39
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 valueReader, Object state) in /home/runner/work/WlxOverlay/WlxOverlay/Protocols/DBus/DBusConnection.cs:line 561
   at Tmds.DBus.Protocol.Connection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 reader, Object readerState) in /home/runner/work/WlxOverlay/WlxOverlay/Protocols/DBus/Connection.cs:line 226
   at WlxOverlay.Desktop.Wayland.XdgScreenData.SelectSourcesAsync() in /home/runner/work/WlxOverlay/WlxOverlay/Desktop/Wayland/XdgScreenCastHandler.cs:line 191
   at WlxOverlay.Desktop.Wayland.XdgScreenData.InitDbusAsync() in /home/runner/work/WlxOverlay/WlxOverlay/Desktop/Wayland/XdgScreenCastHandler.cs:line 77
   at WlxOverlay.Desktop.Wayland.XdgScreenCastHandler.PromptUserAsync(WaylandOutput output) in /home/runner/work/WlxOverlay/WlxOverlay/Desktop/Wayland/XdgScreenCastHandler.cs:line 14
   at WlxOverlay.Core.Subsystem.WaylandSubsystem.CreatePipeWireScreensAsync() in /home/runner/work/WlxOverlay/WlxOverlay/Core/Subsystem/WaylandSubsystem.cs:line 162
   at WlxOverlay.Core.Subsystem.WaylandSubsystem.CreateScreensAsync() in /home/runner/work/WlxOverlay/WlxOverlay/Core/Subsystem/WaylandSubsystem.cs:line 141
   at Program.<Main>$(String[] args) in /home/runner/work/WlxOverlay/WlxOverlay/Program.cs:line 72
   at Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by galister** [comment]
What desktop env is this? All desktop envs that I've seen so far support cursor mode 2.

Also the `libsteam_api.so` error above hints that you didn't have steam/steamvr running before starting wlxoverlay, please make sure steamvr is running before starting it.

**Comment by faux-eccles** [comment]
This is in Plasma KDE though there may have been tweaks to it by the Nobara devs as they repackage some things for their environment.

And Steamvr was running.  I'm having separate issues though where the SteamVR UI fails to run under Wayland.  The compositor starts and I can use the headset and already paired trackers/controllers and launch games.  I just can't use the UI.  To get vrmonitor to start I need to use QT_QPA_PLATFORM=xcb, but then the headset fails

**Comment by galister** [comment]
Are you running an older version? Gnome, Plasma, Weston and wlroots-based compositors are all known to support cursor mode 2.

Maybe hop on the discord / matrix and see if anyone can help we definitely have a couple of Nobara users. Link is in the readme.

**Comment by galister** [comment]
@faux-eccles did you ever figure this out?

**Comment by faux-eccles** [comment]
Apologies, after taking a hammer to my VR installation and smoothing out a number of issues there it's launching much smoother and I can interact with the watch and spawn the desktop displays

```
~/.local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh ./WlxOverlay-v1.4.2-x86_64.AppImage

[eccles@Orionix Downloads]$ ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh ./WlxOverlay-v1.4.2-x86_64.AppImage
vrenv.sh[1462676]: VRCOMPOSITOR_LD_LIBRARY_PATH=/home/eccles/Downloads:/home/eccles/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/eccles/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/eccles/.local/share/Steam/ubuntu12_64/
vrenv.sh[1462676]: exec ./WlxOverlay-v1.4.2-x86_64.AppImage
WlxOverlay v1.4.2
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
OpenVR Version: 2.4.1
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
02/20 21:23:09 Init: Installing breakpad exception handler for appid(250820)/version(2.4.1)/tid(1462720)
IVROverlay_025: pass
IVRCompositor_027: pass
IVRInput_010: pass
crash_20240220212309_2.dmp[1462732]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240220212309_2.dmp
Loaded 10 input actions for /actions/default
export_inputs will not be used.
HMD running @ 90 Hz
crash_20240220212309_2.dmp[1462732]: Finished uploading minidump (out-of-process): success = yes
crash_20240220212309_2.dmp[1462732]: response: CrashID=bp-d13a29f2-7e68-4baa-94c6-34f062240220
crash_20240220212309_2.dmp[1462732]: file ''/tmp/dumps/crash_20240220212309_2.dmp'', upload yes: ''CrashID=bp-d13a29f2-7e68-4baa-94c6-34f062240220''
Wayland detected.
!!! Patched GLFW from https://github.com/Admicos/minecraft-wayland
!!! If any issues with the window, or some issues with rendering, occur, first try with the built-in GLFW, and if that solves the issue, report there first.
!!! Use outside Minecraft is untested, and things might break.
EGL 1.5 initialized.
Using desktop capture protocol: zwlr_export_dmabuf_manager_v1
Using paplay for audio output.
Listening for notifications @ 127.0.0.1:42069
GL Context initialized
[obs-vkcapture] Init Vulkan 1.4.7 (64bit)
[obs-vkcapture] CreateInstance
[obs-vkcapture] CreateInstance VK_SUCCESS
[obs-vkcapture] CreateInstance
[obs-vkcapture] CreateInstance VK_SUCCESS
[obs-vkcapture] CreateDevice
[obs-vkcapture] CreateDevice VK_SUCCESS
[obs-vkcapture] could not get device address for vkCreateSwapchainKHR
[obs-vkcapture] could not get device address for vkDestroySwapchainKHR
[obs-vkcapture] could not get device address for vkQueuePresentKHR
[obs-vkcapture] could not get device address for vkGetSwapchainImagesKHR
```


For context here is a brief summary of the changes to my VR installation, though not finish yet as I still can't access the SteamVR settings, or in VR dashboard:


- Ensure steamvr is installed in a path that doesn't include spaces, preferably one the root fs.

## Update  /home/eccles/local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh 
line 38 to ensure the LD_LIBRARY_PATH in includes a path to the libcef install path
```sh
export LD_LIBRARY_PATH="$(pwd)${SDKDIR+:$SDKDIR/bin/linux64}:$QT_DIR/lib:$STEAMVR_TOOLSDIR/bin/linux64${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}:/home/eccles/.local/share/Steam/ubuntu12_64/"
```
line 39
add `export QT_QPA_PLATFORM=xcb` to ensure all steam QT apps can run.


As per https://github.com/ValveSoftware/SteamVR-for-Linux/issues/579#issuecomment-1878350884 
```
cd ~/.steam/steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/
mv libtcmalloc_minimal.so.0 libtcmalloc_minimal.so.0.bak
ln -s /usr/lib64/libtcmalloc_minimal.so.4 libtcmalloc_minimal.so.0
```

Update `/home/diddums/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup.sh` line 41 
remove `runtime` from vrbindir

**Comment by galister** [comment]
neat. I recommend trying out the rust version of the overlay, it's got some solid performance improvements over this one: https://github.com/galister/wlx-overlay-s
if it doesn't work, you can always hop back on this.
